config {
  type: "table",
  schema: "transform_dataform",
  name: "fact_account",
  description: "Account-wise transaction count with status-wise breakup (SUCCESS / PENDING / FAILED)"
}
 
SELECT
  account_id,
 
  COUNT(transaction_id) AS total_transactions,
 
  COUNTIF(status = 'SUCCESS') AS success_txn_count,
  COUNTIF(status = 'PENDING') AS pending_txn_count,
  COUNTIF(status = 'FAILED')  AS failed_txn_count
 
FROM ${ref("stage_transactions")}
GROUP BY account_id