logsBucket: "gs://x-to-bq-training/bq-dataform_demo/logs"
substitutions:
  _LOCATION: us-central1
  _REPO: dataform-demo
  _PROJECT: neat-striker-447409-t5
  _WORKSPACE: feature-saksham
steps:
  - id: "Create Compilation Result Resource"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    secretEnv: ['DF_CRED']
    args:
      - -c
      - |
        echo "$$DF_CRED" > /workspace/.df-credentials.json
        gcloud auth activate-service-account --key-file=/workspace/.df-credentials.json --project=${_PROJECT} --quiet
        curl -s -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -H "Content-Type: application/json" \
          -d '{"gitCommitish":"dev"}' \
          "https://dataform.googleapis.com/v1beta1/projects/${_PROJECT}/locations/${_LOCATION}/repositories/${_REPO}/compilationResults" \
          | tee /workspace/response.json
        tr -d '\r' < /workspace/response.json > /workspace/response_clean.json


  - id: "Execute Dataform Unit Tests"
    name: "python:3.11"
    entrypoint: "bash"
    args:
      - -c
      - |
        pip install --upgrade pip
        apt-get update && apt-get install -y jq
        pip install google-cloud-bigquery-storage
        pip install dataform-unit-tests
        pip install --no-cache-dir db-dtypes pandas pyarrow
        export COMPILATION_RESULT="$(jq -r '.name' /workspace/response_clean.json)"
        export GCP_PROJECT_ID=neat-striker-447409-t5
        python -m dataform_unit_testing

availableSecrets:
  secretManager:
    - versionName: projects/648723306784/secrets/Dataform-secret/versions/latest
      env: 'DF_CRED'
