logsBucket: "gs://x-to-bq-training/bq-dataform_demo/logs"
substitutions:
  _LOCATION: us-central1
  _REPO: dataform-demo
  _PROJECT: neat-striker-447409-t5
  _WORKSPACE: feature-saksham
steps:
  - id: "Create Compilation Result Resource"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    secretEnv: ['DF_CRED']
    args:
      - -c
      - |
        set -exuo pipefail
        apt-get update && apt-get install -y jq
        echo "$$DF_CRED" > /workspace/.df-credentials.json
        gcloud auth activate-service-account --key-file=/workspace/.df-credentials.json --project=${_PROJECT} --quiet
        _RESPONSE=$(curl -s -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -H "Content-Type: application/json" \
          -d '{"gitCommitish":"dev"}' \
          "https://dataform.googleapis.com/v1beta1/projects/neat-striker-447409-t5/locations/us-central1/repositories/dataform-demo/compilationResults")

        echo "------------------------------- RESPONSE FROM API ----------------------------"
        echo "Response length: ${#_RESPONSE}"
        echo "$_RESPONSE" | jq .
        
        _COMPILATION_RESULT_ID=$(echo "$_RESPONSE" | jq -r '.name')

        echo "------------------------------ COMPILATION_RESULT_ID --------------------------"
        echo "Compilation Result ID length: ${#_COMPILATION_RESULT_ID}"
        echo "Compilation Result ID: ${_COMPILATION_RESULT_ID}"
        
        echo "$_COMPILATION_RESULT_ID" > /workspace/compilation_result_id.txt
        echo "-------------------------------------------------------------------------------"
        cat /workspace/compilation_result_id.txt
        echo "-------------------------------------------------------------------------------"



  - id: "Execute Dataform Unit Tests"
    name: "python:3.11"
    entrypoint: "bash"
    args:
      - -c
      - |
        pip install --upgrade pip
        pip install dataform-unit-tests
        pip install --no-cache-dir db-dtypes pandas pyarrow
        export COMPILATION_RESULT="projects/neat-striker-447409-t5/locations/us-central1/repositories/dataform-demo/compilationResults/48fcbfeb-66e3-4322-9fad-3c20493adef8"
        export GCP_PROJECT_ID=neat-striker-447409-t5
        python -m dataform_unit_testing

# export COMPILATION_RESULT="$(cat /workspace/compilation_result_id.txt)"

availableSecrets:
  secretManager:
    - versionName: projects/648723306784/secrets/Dataform-secret/versions/latest
      env: 'DF_CRED'
